// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qikrlbfajdzfubcjykxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpa3JsYmZhamR6ZnViY2p5a3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY4OTgsImV4cCI6MjA2NTQ5Mjg5OH0._4va337SZluNxyNZYgHfvQu_ERu0n_PnmnyirVXXgOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);